name: Metrics
on:
  # Schedule updates (each 6 hours)
  # schedule: [{cron: "0 */6 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: "Europe/London"
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_lines: yes
      - name: Detailed Achievements, Reactions & Coding Habits
        # uses: lowlighter/metrics@latest
        # uses the commit fork https://github.com/stalomeow/metrics/commit/edcae0f874d69e509d25ddd5e750a2f41cd54e10 
        # until https://github.com/lowlighter/metrics/issues/1706 is fixed in lowlighter.
        uses: stalomeow/metrics@edcae0f874d69e509d25ddd5e750a2f41cd54e10
        with:
          filename: metrics-achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_order: achievements, reactions, habits
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_limit: 18
          plugin_reactions: yes
          plugin_reactions_limit: 500
          plugin_reactions_limit_issues: 200
          plugin_reactions_details: count, percentage 
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Europe/London
