name: Metrics
on:
  # Schedule updates (every 12 hours)
  #schedule: [{cron: "0 */12 * * *"}]
  # Manual workflow run
  workflow_dispatch:
  # Run workflow when pushing to master
  # push: {branches: ["master", "main"]}
  
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Debug info
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Running on: $RUNNER_OS"
          echo "Free disk:"
          df -h
          echo "Free memory:"
          free -h
      - name: Metrics
        uses: stalomeow/metrics@projects-v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bwhybrow23
          filename: metrics.svg
          base: header
          base_indepth: yes
          config_timezone: Europe/London
          plugin_languages: yes
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
