name: Metrics
on:
  # Schedule updates (every 12 hours)
  schedule: [{cron: "0 */12 * * *"}]
  # Manual workflow run
  workflow_dispatch:
  # Run workflow when pushing to master
  # push: {branches: ["master", "main"]}
  
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Full-year calendar
        uses: stalomeow/metrics@projects-v2
        with:
          filename: metrics-isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: bwhybrow23
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Achievements
        if: ${{ success() || failure() }}
        uses: stalomeow/metrics@projects-v2 # lowlighter/metrics@latest
        with:
          filename: metrics-achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: bwhybrow23
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
      - name: General
        if: ${{ success() || failure() }}
        uses: stalomeow/metrics@projects-v2
        with:
          filename: metrics-general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: bwhybrow23
          base: header
          base_indepth: yes
          config_timezone: "Europe/London"
          plugin_languages: yes
          plugin_lines: yes
