name: generate animation

on:
  # run automatically every 6 hours
  schedule: [{cron: "00 0 * * 1"}]
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the main branch
  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: "bwhybrow23"
          outputs: dist/github-contribution-grid-snake.svg
